config/routes.rb
Rails.application.routes.draw do

  resources :users

  root 'welcome#index'

  get 'logout', to: 'sessions#delete'
  delete 'logout', to: 'sessions#delete'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

    resources :props do
      resources :comments
      resources :answers

    end

end

app/models/prop.rb
class Prop < ActiveRecord::Base
  has_attached_file :propimage,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

                    validates_attachment_content_type :propimage, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def s3_credentials
    {:bucket => "propsbucket", :access_key_id => ENV["ACCESS_KEY_ID"], :secret_access_key => ENV["SECRET_ACCESS_KEY"], :s3_region => 'us-east-1'}
  end



  belongs_to :user
  has_many :comments
  has_many :answers
end

app/controllers/props_controller.rb
class PropsController < ApplicationController
  attr_accessor :user, :answer, :choice, :prop_id, :prop, :answer_id, :id, :propimage
  # before_action :require_login, only: [:show]

  def index

    @props=Prop.all

    if logged_in?
    @user = User.find(session[:user_id])
    end
  end

  def show
    @prop = Prop.find(params[:id])
    if logged_in?
      @user = User.find(session[:user_id])
    end
  end

  def new
    @prop = Prop.new
    @user = User.find(session[:user_id])

  end

  def edit
    @prop = Prop.find(params[:id])
    @user = User.find(1)
  end

  def create
    @prop = Prop.new(prop_params)
    @user = User.find(session[:user_id])

    @answer = Answer.new

    if @prop.save
      redirect_to @prop
    else
      render 'new'
    end

  end

  def update
       @prop = Prop.find(params[:id])
       # @user = User.find(1) #hardcoded to be admin
       @prop.update(prop_params)

       Answer.all.each  do |answer|
         @user = User.find(answer.user_id)
         if (answer.prop_id == @prop.id)
           if (answer.choice == @prop.choice)
             @user.score  += 5
             @user.save
           else
             @user.score  -= 5
             @user.save
           end
         end
       end
       redirect_to users_path
   end

  def destroy
    @prop = Prop.find(params[:id])
    @prop.destroy

    redirect_to props_path
  end

  def select
    @prop = Prop.find(params[:choice])
  end

  # def require_login
  #   if !logged_in?
  #     flash[:danger]="You must login perform that action"
  #     render 'users/pleaselogin'
  #   end
  # end

end

private
  def prop_params
    params.require(:prop).permit(:title, :text, :choice, :user_id, :id, :propimage)
  end

app/helpers/props_helper.rb
module PropsHelper
end

app/views/props/_form.html.erb
<%= form_for @prop, html: { multipart: true } do |f| %>

  <% if @prop.errors.any? %>
    <div class="error_explanation">
      <h2>
        <%= pluralize(@prop.errors.count, "error")  %>
prohibited this prop from being saved:
      </h2>
      <ul>
        <% @prop.errors.full_messages.each do |msg|  %>
        <li><%= msg  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>


  <%= f.radio_button(:choice, "A") %>
  <%= f.label(:choice, "The Correct Answer is A") %></br >
  <%= f.radio_button(:choice, "B") %>
  <%= f.label(:choice, "The Correct Answer is B") %></br >
  <%= f.radio_button(:choice, "C") %>
  <%= f.label(:choice, "The Answer Has Yet To Be Determined") %>
  <%= f.label(:propimage, "Add an image to this bet") %>
  <%= f.file_field :propimage %>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <%= f.hidden_field :prop_id, :value => @prop.id %>

  <p>
     <button class="btn btn-positive btn-block btn-outlined"><%= f.submit %></button>

  </p>
<% end %>

app/views/props/_prop.html.erb
<% obj.each do |prop| %>

<div>
<h3><%= link_to prop.title, prop %></h3>
<p><%= prop.text %></p>
<h3><%= link_to 'Show', prop %></h3>
<h3><%= link_to 'Edit', edit_prop_path(prop) %></h3>
<h3><%= link_to 'Delete', prop_path(prop),
                          method: :delete,
                          data: ( 'Are you sure?' ) %></h3>

</div>

<% end %>

app/views/props/edit.html.erb
<div class="content">

<%= render 'form' %>


<%= link_to 'Back to All Props', props_path  %>
</div>

app/views/props/index.html.erb
<div class="content allpropsul">
  <% @props.reverse.each do |prop| %>
    <ul class="table-view ">
      <li class="table-view-cell media">
        <a href=props/<%= prop.id %> >
          <%= image_tag prop.propimage.url, :class => "propindeximage media-object pull-right"  %>
          <h5><%= prop.title %></h5>
          <p class="proplistp"><%= prop.text %></p>
            <div>
              <% if logged_in? and current_user.admin %>
                <button class="btn " class="btn pull-left">
                  <%= link_to 'Edit', edit_prop_path(prop) %>
                </button>
                <button class="btn " class="btn pull-right">
                  <%= link_to 'Delete', prop_path(prop),
                                            method: :delete,
                                            data: ( 'Are you sure?' )
                                             %>
                </button>
            </div>
                <% end %></br >
        </a>
      </li>
    </ul>
  <% end %>
</div>

app/views/props/new.html.erb
<h1>Create A New Prop</h1>

<%= render 'form' %>

app/views/props/pleaselogin.html.erb
<div class="content">
<h1>You must be logged in to view open bets!</h1>
</div>



    <%= link_to(login_path) do %>
      <button class="btn pull-left">
        Login
      </button>
    <% end %>
    <%= link_to(new_user_path) do %>
      <button class="btn pull-right">
        Sign Up
      </button>
    <% end %>

app/views/props/show.html.erb
<div class="content">
  <% if logged_in? && current_user.admin? %>

  <div class="bar bar-standard bar-header-secondary">
      <button class="btn btn-block edit">  <%= link_to 'Update this Bet', edit_prop_path(@prop)%></button>
    </div>
    <% end %>

    <br>
    <br>




    <div class="content-padded">
        <div style="text-align:center;">
          <%= image_tag @prop.propimage.url, :class => "propshowimage"%>
        </div>
        <h5 style="font-size:19px;">
          <strong><%= @prop.title %></strong>
        </h5>

        <p class="p show">
          <%= @prop.text %>
        </p>
    </div>

<div class="bar bar-standard bar-footer-secondary">
        <button class="btn btn-block">
            <% if logged_in?%>
              <%= link_to 'Place a Bet', new_prop_answer_path(@prop)  %>
            <% else %>
              <%= link_to 'Login to place a bet', login_path  %>
            <% end %>
        </button>
</div>
 </div>

app/views/props/update.html.erb
<%= render 'form' %>


<%= link_to 'Back to All Props', props_path  %>