config/routes.rb
Rails.application.routes.draw do

  resources :users

  root 'welcome#index'

  get 'logout', to: 'sessions#delete'
  delete 'logout', to: 'sessions#delete'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

    resources :props do
      resources :comments
      resources :answers

    end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

                    validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def s3_credentials
    {:bucket => "propsbucket", :access_key_id => ENV["ACCESS_KEY_ID"], :secret_access_key => ENV["SECRET_ACCESS_KEY"], :s3_region => 'us-east-1'}
  end



  has_many :props, dependent: :destroy
  has_many :answers
  has_many :user_answers
  has_many :answers, through: :user_answers
  has_many :created_answers, :class_name => "Answer", :foreign_key => "created_by"
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  has_secure_password


  before_save { self.email = email.downcase }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessor :user, :answer, :choice, :prop_id, :prop, :answer_id, :id, :avatar

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @user = User.find(session[:user_id])

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @prop = Prop.all
    @user = User.find(session[:user_id])

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger]="Only admin users can perform that action"
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, url: users_path, :html => {class: "form-horizontal", role: "form", multipart: true}) do |f| %>
     <div class="form-group">
       <div class="control-label col-sm-2">
         <%= f.label :username %>
       </div>
       <div class="col-sm-8">
         <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
       </div>
     </div>
     <div class="form-group">
       <div class="control-label col-sm-2">
         <%= f.label :email %>
       </div>
       <div class="col-sm-8">
         <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
       </div>
     </div>
     <div class="form-group">
       <div class="control-label col-sm-2">
         <%= f.label :password %>
       </div>
       <div class="col-sm-8">
         <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
       </div>
     </div>

     <div class="form-group avatarbutton">
       <div class="control-label col-sm-2">
         <%= f.label :avatar %>
       </div>
       <div class="col-sm-8">
         <%= f.file_field :avatar %>
       </div>
     </div>

     <div class="form-group">
       <div class="col-sm-offset-2 col-sm-10">
         <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-block btn-outlined') %>
       </div>
     </div>
   <% end %>

app/views/users/edit.html.erb
<div class="content"> 
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
</div>

app/views/users/index.html.erb
<div class="content">
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.score %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/pleaselogin.html.erb
<div class="content">
<h1>You must be logged in to view open bets</h1>

<div>
<%= link_to(login_path) do %>
    Login
<% end %>

<%= link_to(new_user_path) do %>
    Sign Up
<% end %>
</div>

</div>

app/views/users/show.html.erb
<div class="content">

  <div>
    <div style="text-align:center;">
      <h5 class="username"><%= @user.username %></h5>
      <%= image_tag @user.avatar.url %>
      <p style="color:#428bca;">score: <%= @user.score %></p>
    </div>
    <p>
      <button class="btn btn-block">Edit Profile</button>
    </p>
  </div>


<% if logged_in? and current_user.admin %>
  <div class="card">

    <ul class="table-view">
      <li class="table-view-cell">
          <%= link_to 'View All Bets', controller: 'props'  %>
      </li>
      <li class="table-view-cell">
          <%= link_to 'Create a Bet', new_prop_path  %>
      </li>
      <li class="table-view-cell">
          <%= link_to 'View All Users', users_path  %>
      </li>
    </ul>
  </div>

<% end %>




<% @prop.reverse.each do |prop| %>

<ul class="table-view ">
  <li class="table-view-cell media">
    <a href=/props/<%=prop.id%> >
      <img class="media-object pull-right" style="text-align: right; margin-right:-50px;" src="http://placehold.it/82x82">

      <h5><%= prop.title.capitalize %></h5>
      <p class="proplistp"><%= prop.text %></p>
      <div>

          <% if logged_in? and current_user.admin %>
            <button class="btn " class="btn pull-left">
              <%= link_to 'Edit', edit_prop_path(prop) %>
            </button>
            <button class="btn " class="btn pull-left">
              <%= link_to 'Delete', prop_path(prop),
                                        method: :delete,
                                        data: ( 'Are you sure?' )
                                         %>
            </button>
        </div>

            <% end %></br >
    </a>
  </li>
</ul>

<% end %>







</div>