config/routes.rb
Rails.application.routes.draw do

  resources :users

  root 'welcome#index'

  get 'logout', to: 'sessions#delete'
  delete 'logout', to: 'sessions#delete'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

    resources :props do
      resources :comments
      resources :answers

    end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :prop
  belongs_to  :created_by, :class_name => "User", :foreign_key => "created_by"
  has_many :users
  has_many :user_answers
  has_many :users, through: :user_answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  attr_accessor :user, :answer

  def index

  end

  def new
    @prop = Prop.find(params[:prop_id])

    @user = User.find(session[:user_id])

    @answer = Answer.new

  end

  def create
    @prop = Prop.find(params[:prop_id])
    @user = User.find(session[:user_id])
    @answer = @user.answers.create(answer_params)
    @answer.user_id = @user.id

    if @answer.save
      puts "Saved: " + @answer.choice
      redirect_to root_path
    else
      render 'new'
    end
  end


  def show
    @answer = Answer.find params[:id]

  end
end

private
def answer_params

  params.require(:answer).permit(:choice, :id, :prop_id, :prop)
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/new.html.erb
<div class="content">
<div class="content-padded">



<%= form_for :answer, url: prop_answers_path do |f| %>


  <%= f.radio_button(:choice, "A") %>
  <%= f.label(:choice, "The Correct Answer is A") %>
  <hr/>
  <%= f.radio_button(:choice, "B") %>
  <%= f.label(:choice, "The Correct Answer is B") %>

  <%= f.hidden_field :prop_id, :value => @prop.id %>

   <p>
     <button class="btn btn-positive btn-block"><%= f.submit %></button>

  </p>
<% end %>

</div>
</div>

app/views/answers/show.html.erb
<p> You chose choice <%= @answer.choice %></p>
<p>If you are correct, your balance will be incremented when the bet is complete</p>

app/views/answers/thankyou.html.erb
<h1>Thanks</h1>